apiVersion: apps/v1
kind: Deployment
metadata:
   name: simpleapp
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: simpleapp
   template:
      metadata:
         labels:
            app: simpleapp
      spec:
         containers:
            - name: simpleapp
              image: gcr.io/simple-app-project-413304/default-artifact-registry/simpleapp
---
apiVersion: v1
kind: Service
metadata:
   name: simpleapp
   namespace: default
spec:
   type: LoadBalancer
   selector:
      app: simpleapp
   ports:
      - port: 9000
        targetPort: 9000
